name: Dupligit Bot – Detect Duplicates on Issue

on:
  issues:
    types: [opened]

jobs:
  detect-duplicate:
    runs-on: ubuntu-latest

    steps:
      - name: 🔍 Extract issue info
        run: |
          echo "Issue Title: ${{ github.event.issue.title }}"

      - name: 🌐 Query /predict endpoint
        run: |
          RESPONSE=$(curl -s -X POST https://c6af-176-42-23-181.eu.ngrok.io/predict \
            -H "Content-Type: application/json" \
            -d "{\"text\": \"${{ github.event.issue.title }}\"}")
          echo "$RESPONSE"

          COMMENT="🤖 Dupligit Bot says this might be a duplicate:\n\n$RESPONSE"

          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \
            -d "{\"body\": \"$COMMENT\"}"
